### ISSUE TITLE
XS view doesn't showing "burger menu"

### ISSUE THREAD

**Issue by slegouffe** [chrisgriffith/IonicSplitPaneDemo#1]
![capture d ecran 2017-03-10 a 00 21 04](https://cloud.githubusercontent.com/assets/315404/23775167/8ffd72ae-0527-11e7-95cb-3fa8576f823c.png)
Hi ! 

Thank you so much for your sample of the new Ionic 2 split pane feature. I try your code and it works as expected, but when I change my screen size, from md to xs (phone) I didn't show the "burger menu" which is supposed to display the main menu when we tap on it...Any ideas ? 

Thks !

**Comment by chrisgriffith** [comment]
With the 'inception' nav demo, we in effect kill the hamburger menu from appearing (which the 'standard' split pane will do automatically). You can manually add the control back to the top level of the nav stack. The tricky part would be as you navigate through the main content stack, deciding what to do? Show the hamburger or show the navigation control?

In main.html make this change to have it appear on the top level:
````
<ion-navbar>
  <button ion-button icon-only menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>Main</ion-title>
</ion-navbar>
````

**Comment by slegouffe** [comment]
Thanks for the tips !
